### ISSUE TITLE
Audit and adjust AWS Account Usage and Names

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#187]
When checking aws cloudtrail logs during an incident, we noticed that the names of our AWS IAM accounts are not up to date and not unique. Clear names would help to identify who (or which programmatic service) did what changes in the cloud instantly.

The cloudtrail logs shall be checked for IAM usernames, and the IAM usernames shall be adjusted to correctly reflect their permissions and usage. The name should include for example the deployment (`staging` vs `production`)

**Comment by mrnicegyu11** [comment]
Actions:
- [ ] add aws account for all backend users
- [ ] add aws-tags to infrastructure where possible

**Comment by YuryHrytsuk** [comment]
Done but some improvements are possible later. Closing for now
