### ISSUE TITLE
e2e-ops: Rename branch names

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#201]
Branch names on the e2e-ops repo are "colloquial" and dont reflect any actual architecture.
The branch names of `osparc-ops-deployment-configuration` are much more reasonable, they use the fully-qualified-domain-name (FQDN, read: DNS Name) of the primary oSparc product of the respective deployment.

The branch names in e2e-ops should be made identical to the `DEPLOYMENT_FQDN` variable

**Comment by YuryHrytsuk** [comment]
this is done
