### ISSUE TITLE
e2e-ops: Remove hardcoded credentials.

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#202]
Switch hardcoded credentials to access tokens for pgbackup and mail-server e2e-ops-test. Some login credentials to github are hardcoded. We can switch this to access tokens for better security and manageability. This is not urgent/critical.

**Comment by YuryHrytsuk** [comment]
Tracked in https://github.com/ITISFoundation/osparc-ops-environments/issues/189
