### ISSUE TITLE
Upgrade all machines to latest docker engine version

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#215]
~~This PR removes the docker version pin: https://github.com/ITISFoundation/osparc-simcore/pull/3941
This one is required by the above: https://github.com/ITISFoundation/osparc-simcore/pull/3974
This PR is required by the second: https://github.com/ITISFoundation/osparc-simcore/pull/4055~~

This was unblocked recently by https://github.com/ITISFoundation/osparc-simcore/pull/4212

CC @GitHK 
```[tasklist]
### Tasks
- [x] master
- [x] dalco
- [x] aws-staging
- [x] aws-prod
- [x] aws-autoscaling
- [ ] tip.itis.swiss
```

**Comment by GitHK** [comment]
@sanderegg I wonder about computational services if they can swap out the constraints for labels or if you have issues doing so.

**Comment by YuryHrytsuk** [comment]
Only TIP is left. Let's nail this issue :rocket:

**Comment by mrnicegyu11** [comment]
tip.itis.swiss will be phsaed out in favor of tip.science, where the up2date docker engine version will be rolled out. This issue can thus be closed
