### ISSUE TITLE
Synchronise all timezones in monitoring stack

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#232]
- The e2e (gitlab runners) times are set in UTC.
- The grafana dashboards are set in Zurich Time (UTC+2).
- graylog is on UTC
- portainer is also not on UTC

It would be desirable to have all these guys in the same time zone. For simplicity I would recommend UTC.

**Comment by YuryHrytsuk** [comment]
too difficult for the benefit we get
