### ISSUE TITLE
Add a e2e-ops test that checks bucket lifecycle / versioning and asserts it is set as desired

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#237]
Add a e2e-ops test that checks bucket lifecycle / versioning and asserts it is set as desired

**Comment by YuryHrytsuk** [comment]
in AWS it is done via Terraform state test
in in-house it is done via CEPH state test ([find more info here](https://github.com/ITISFoundation/osparc-ops-environments/issues/706))
