### ISSUE TITLE
Redundancy for simcore services on aws-prod :warning: DEVOPS

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#242]
Currently there is only one node properly running simcore services, there should be at least 2

**Comment by YuryHrytsuk** [comment]
@mrnicegyu11 do you think we can reuse one of the many machines we have in AWS PROD? For example, one of the 3 managers we have?

**Comment by YuryHrytsuk** [comment]
We have set up an EC2 instance. I am trying to add it to the running aws staging. At the moment, docker containers run on a newly-added node have network issues. Once I manage to run containers on this node smoothly, we will add this node to AWS Prod and introduce HA for Simcore Services

**Comment by YuryHrytsuk** [comment]
The new machine has been added. It will only allocate simcore services (no rabbit / redis) as of now.

Related PRs:
* https://git.speag.com/oSparc/osparc-infra/-/merge_requests/172
* https://git.speag.com/oSparc/e2e-ops/-/merge_requests/97
