### ISSUE TITLE
Grafana import for tip deploy is failing

### ISSUE THREAD

**Issue by Surfict** [ITISFoundation/osparc-ops-environments#248]
When importing grafana dashboards on the tip deployment - service monitoring, the scripts launched with
```
make grafana-import
``` 
fails with

> ERROR: Config file missing at: ../provisioning/tip.itis.swiss/datasources2dashboards.yaml
make: *** [Makefile:103: grafana-import] Error 1

**Comment by mrnicegyu11** [comment]
Fixed by https://github.com/ITISFoundation/osparc-ops-environments/commit/87a51141c9969c20f73d2bd87914823e20002116
