### ISSUE TITLE
new */prometheuscadvisor redirect issue

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#253]
Please make sure that the new */prometheuscadvisor is accessible for all deployments (ex. in aws staging, i can see there is similar problem with redirecting to */prometheus-cadvisor which causes problems) Thanks!

**Comment by mrnicegyu11** [comment]
Thanks for the ticket.
This was fixed by re-dploying the monitoring stack everywhere.
