### ISSUE TITLE
pgsql-query-exporter fails to log into pgsql on dalco-staging

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#262]
From the logs of this pgsql-query-exporter prometheus exporter it seems that the password is wrong. This is a bug.

**Comment by mrnicegyu11** [comment]
we will close this ticket once we are sure the changes work in dalco-staging

**Comment by YuryHrytsuk** [comment]
> we will close this ticket once we are sure the changes work in dalco-staging

It requires releae to dalco production. As soon as we release to dalco production, we will verify that the fix works correctly and close this issue

**Comment by YuryHrytsuk** [comment]
After the release, this issue has been fixed

```2023-09-29 07:38:37,431 - DEBUG - query-exporter - connected to database "postgres_staging"```

**Comment by YuryHrytsuk** [comment]
In order to see DEBUG logs, I enabled debug logs on `pgsql-query-exporter` service by introducing `command: ["-L", "DEBUG"]` command in the `pgsql-query-exporter` service

https://github.com/albertodonato/query-exporter#debugging--logs

**Comment by mrnicegyu11** [comment]
thanks a lot
