### ISSUE TITLE
Ansible fails while adding a new machine to the swarm cluster

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#264]
### The problem
The task `Register the name of the new created partition` returns an empty string which causes failures later

### Location
`osparc-infra/ansible/playbooks/config/docker-dedicated-HD/volumes-config.yml`

### Details
The bash command `lsblk | grep -E {{dedicated_docker_volume_lsblk_size}} | head -n1 | awk '{print $1;}' | cut -c 7-` might improperly interpolate `{{dedicated_docker_volume_lsblk_size}} `. The `cut -c 7-` could also create a problem

**Comment by mrnicegyu11** [comment]
This happened upon the re-installation of machine `master07`

**Comment by mrnicegyu11** [comment]
This is partially addressed by https://git.speag.com/oSparc/osparc-infra/-/merge_requests/150
