### ISSUE TITLE
Roll out AWS managed rabbitmq with replication

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#283]

**Comment by mrnicegyu11** [comment]
Tracked by https://github.com/ITISFoundation/osparc-issues/issues/1018

**Comment by mrnicegyu11** [comment]
This seems blocked by simcore not being able to handle the `amqps` protocoll (currently only `amqp`). Please follow up @sanderegg

**Comment by mrnicegyu11** [comment]
Blocked until https://github.com/ITISFoundation/osparc-simcore/pull/4567 propagates to staging/prod

**Comment by mrnicegyu11** [comment]
We use it now in the ZMT deployment. It is in.

**Comment by YuryHrytsuk** [comment]
Amazom MQ Cluster deployment for high availability:
* https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-broker-architecture-cluster.html

**Comment by YuryHrytsuk** [comment]
Amazon broker config reference:
* https://docs.aws.amazon.com/amazon-mq/latest/api-reference/brokers.html

Terraform `aws_mq_broker` doc:
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker
  - different `deployment_mode` require special adjustments (e.g. with subnets). Be careful

**Comment by YuryHrytsuk** [comment]
:warning: The `mq.t3.micro` instance type does not support [cluster deployment](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-broker-architecture-cluster.html).

**Comment by YuryHrytsuk** [comment]
aws mq broker instance types
* https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/broker-instance-types.html

**Comment by YuryHrytsuk** [comment]
replicated RabbitMQ for sim4life.io:
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/194
