### ISSUE TITLE
Decouple AWS release process

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#284]
Idea: have new tags: "aws-staging", "aws-production" for releases. Auto-deployer should look for this tags in AWS deployments

**Comment by mrnicegyu11** [comment]
Please explain this more verbosely @matusdrobuliak66 , ideas are appreciated but I dont understand what exactly the goal is or what painpoints this would address

**Comment by matusdrobuliak66** [comment]
By introducing a bit more degree of freedom by having separate tags for releasing for different deployments we decouple the release logic a bit which will be more flexible/error prune. (My main focus here is on ZMT, I do not want to block ZMT usage because of some in-house maintenance/issues) 

Also If we are doing hotfix/or even regular releases for some reason just for one deployment (ex. we need to release urgently to ZMT deployment). We do not need to put down all the auto-deployment agents from other deployments (where is a risk of human error/ also there is a risk that the auto-deployment agent will be turned on for some reason) 

Yes for sure when we have a lot of deployments we should always deploy everything so we do not diverge too much. But in situations when we need to diverge in my opinion this will be more comfortable/maintainable. Basically, it is a preparation for untypical situations which will for sure occur.

**Comment by mrnicegyu11** [comment]
this doesnt apply anymore since the deployment-agent was removed and archived
