### ISSUE TITLE
Activate access-logs in traffik in master

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#290]
I would like to trace why queries are returning with [502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502)

**Comment by mrnicegyu11** [comment]
Can the access logs be deactivates and then this ticket be closed @pcrespov ?

**Comment by pcrespov** [comment]
> Can the access logs be deactivates and then this ticket be closed @pcrespov ?

@mrnicegyu11 Yes, I found what I was looking for and you can deactivate access logs when you like. thx
