### ISSUE TITLE
[Costs] Review EBS volumes

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#294]
Please review how we use EBS volumes, mainly:
 - provisioned storage
 - snapshots

They burn a lot of money, so maybe we may optimize, but for that, we need to understand how we are working with them.

**Comment by mrnicegyu11** [comment]
We removed the aws backup plan as it is not needed anymore. The snapshots should be automatically deleted after the 90day retention window passed
