### ISSUE TITLE
[Costs] Idea: create test for checking running EC2 instances

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#295]
This is just an idea. Maybe we should have a test, that checks all currently running EC2 instances and compares them with list of instances that are expected to run. This would help us to capture earlier if there is some running EC2 instance that should not be running.

**Comment by mrnicegyu11** [comment]
This is unfeasible with auto-scaling at our current codebase, it is too complicated for now. It is captured implicitly by the cost test.
