### ISSUE TITLE
Fix email credentials in staging 

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#319]
pls check credentials for email in `staging` aws email

https://monitoring.osparc-staging.io/graylog/messages/graylog_160/b98ee3a1-3ff9-11ee-b601-0242ac12001a

TIP: to check the email settings you can use https://staging.osparc.io/dev/doc#/admin/test_email entrypoint

**Comment by YuryHrytsuk** [comment]
These variables are missing in all deployments!
* SMTP_PASSWORD
* SMTP_USERNAME
* SMTP_PROTOCOL
