### ISSUE TITLE
Reduce number of buffer machines for s4l-lite

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#320]
Please setup this variable `EC2_INSTANCES_MACHINES_BUFFER` in AWS production to 1.

1 buffer machine is enough to save some money.

**Comment by mrnicegyu11** [comment]
@matusdrobuliak66 yury asks me to ask you if this needs to be done in the coming sprint

**Comment by matusdrobuliak66** [comment]
Yes please we could have already saved a lot of money. I guess it is just a change in one ENV variable. Thanks!

**Comment by YuryHrytsuk** [comment]
Done in this commit: 
https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/commit/e9efae534ccf31a758915d34fde503a0c9fb7c2f
