### ISSUE TITLE
Introduce payments simcore service

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#331]
The service was implemented and brought in in https://github.com/ITISFoundation/osparc-simcore/pull/4676

- Expose `payments.*` subdomain and reconnect to the payments service (similar to the `invitations`). Make sure that
   a) path `/v1/*` is accessible (will use auth defined in service)
   b) otherwise, it is password protected by the reverse-proxy
- Double-check all env-vars configuration for this service

**Comment by mrnicegyu11** [comment]
Blocked waiting for @pcrespov

**Comment by pcrespov** [comment]
> Blocked waiting for @pcrespov

- We will address this as soon as the `payments` service is fully functional and our partners have the gateway online. 
- Short update: payment service goes through its second iteration in https://github.com/ITISFoundation/osparc-simcore/pull/4743. For the moment I think it will need in total four iterations (i.e. 2 more).

**Comment by YuryHrytsuk** [comment]
All is done.
