### ISSUE TITLE
AWS Staging Director-v2 variable is wrong

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops-environments#342]
This current ENV defined on director-v2 is wrong:
- ```DIRECTOR_V2_SERVICES_CUSTOM_CONSTRAINTS=[\"node.labels.io.simcore.autoscaled-node!=true\"]```

It should be set to:
- ```DIRECTOR_V2_SERVICES_CUSTOM_CONSTRAINTS=[]```

**Comment by YuryHrytsuk** [comment]
https://github.com/ITISFoundation/osparc-ops-environments/issues/343

**Comment by YuryHrytsuk** [comment]
The `DIRECTOR_V2_SERVICES_CUSTOM_CONSTRAINTS` is now set to `[]` in AWS Staging
