### ISSUE TITLE
AWS Staging autoscaling KEYNAME ENV variable is wrong

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops-environments#343]
After the rotation of the KEYPAIRS, the ENV wasn't updated accordingly.

This currently has no effect I think.

But the side-effect is that changing it makes the old instances to fail:
https://github.com/ITISFoundation/osparc-simcore/issues/4722

**Comment by YuryHrytsuk** [comment]
The new key pair name is correctly configured in `osparc-ops-deployment-configuration` for aws staging and aws production
