### ISSUE TITLE
Update password for portainer fails with special characters

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#344]
`make secrets` fails in portainer service if the password contains special characters.

Either:
- Fix `make secrets` in `services/portainer` to allow usage of special characters in portainer password
or:
- Use non-official approach using docker secrets and  `make secrets` in `services/portainer` and add a comment to NOT add special characters into the Portainer password

**Comment by mrnicegyu11** [comment]
https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/wikis/Update-Portainer-Password

**Comment by mrnicegyu11** [comment]
not an issue at the moment

**Comment by YuryHrytsuk** [comment]
When portainer pwd secret is not presented, the `secrets` target in Makefile fails to create a new secret and, thus, cannot create a portainer stack

``` bash
Updating secret portainer_admin_password
.env: line 1: unexpected EOF while looking for matching `"'
.env: line 4: syntax error: unexpected end of file
make: *** [Makefile:89: secrets] Error 1
```

**Comment by YuryHrytsuk** [comment]
As a workaround, one can always create a secret manually from file. Comment `secrets` dependency in necessary target (e.g. `up-aws`) and run `make up-<stack>`

**Comment by YuryHrytsuk** [comment]
Overview:
* Ops code cannot properly handle special chars in the variables
  - The problem is `envsubst` remove any escape characters and then `source .env` can easily fail
* The issue is fixed by using Portainer password without special chars
