### ISSUE TITLE
Traefik: Router defined multiple times with different configurations

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#345]
Full error log from traefik logs:
```
time="2023-09-11T12:34:56Z" level=error msg="Router defined multiple times with different configurations in [monitoring-prometheuscadvisor-ruvumt9ys7pmzrc53nviavffm monitoring-prometheuscatchall-vte3irdacy9knkxctzs3cahhw]" routerName=prometheus providerName=docker
```

it is most likely caused by the fact that `traefik.enable=true` and we have 2 different services based on the same image. Thus, the routers with the same name (image name) is created multiple times? it is [YH] assumption

**Comment by mrnicegyu11** [comment]
it's done
