### ISSUE TITLE
Remove "all" credetials

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#353]
https://git.speag.com/oSparc/osparc-infra/-/issues/33

- github 
- mattermost 
- gitlab
- dockerhub 
- statuspage
- AWS x3

**Comment by YuryHrytsuk** [comment]
I changed Portainer password in AWS Produciton. When we release, we need to change S3 Access Key and Postgres Password

**Comment by YuryHrytsuk** [comment]
The S3 Access Key and Postgres password rotation on AWS PROD is scheduled for the next release: 

https://github.com/ITISFoundation/osparc-simcore/issues/4807

**Comment by mrnicegyu11** [comment]
We need to change the ACCESS/SECRETS of the ceph buckets of tip.itis.swiss.

**Comment by YuryHrytsuk** [comment]
Monitor the progress here: https://git.speag.com/oSparc/osparc-infra/-/issues/33

**Comment by YuryHrytsuk** [comment]
Should be closed after v1.64.0 release
