### ISSUE TITLE
Fix Dalco 13 (networking issues aftermath)

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#355]
pending

**Comment by YuryHrytsuk** [comment]
The incident report has been created here: https://git.speag.com/oSparc/osparc-infra/-/issues/35. Following this incident, will be added tests that will test dns resolution and floating IP allocation to automatically detect network issues that occurred recently.

**Comment by YuryHrytsuk** [comment]
The tests that check the issues that have occurred during this incident: https://github.com/ITISFoundation/osparc-ops-environments/issues/379

**Comment by YuryHrytsuk** [comment]
The only task left is to write a helper Readme that will help to discover / trace / identify / debug network issues that have occurred during this incident and ideas how to test network that appeared during this incident

**Comment by YuryHrytsuk** [comment]
This instructions describing how to trace / debug / resolve issues can be found here:

https://git.speag.com/oSparc/osparc-infra/-/issues/35#lessons-learned

**Comment by YuryHrytsuk** [comment]
It will be closed once we fix Dalco 6 and 13 machines

**Comment by mrnicegyu11** [comment]
Dalco13 is with IT Support atm

**Comment by mrnicegyu11** [comment]
To-Do: Ping Andrea, get status update

**Comment by YuryHrytsuk** [comment]
We decided to give up on Dalco 13. In case we need it back we can reopen this issue.
