### ISSUE TITLE
Fix dalco01 RAID missing one drive

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#363]
This is urgent

**Comment by mrnicegyu11** [comment]
This is still the case, assigning YH

**Comment by YuryHrytsuk** [comment]
### Literature

* [A good article about re-adding "remove" drive to Raid](https://superuser.com/questions/1742014/determine-why-drive-was-removed-from-software-raid-array-and-rebuild-safely)

**Comment by YuryHrytsuk** [comment]
Fixed by executing a command `sudo mdadm --manage /dev/md0 --add /dev/sde`

A PR that adds a tests monitoring the health of dalco 01 RAID:
https://git.speag.com/oSparc/e2e-ops/-/merge_requests/115

**Comment by YuryHrytsuk** [comment]
Incident report: https://git.speag.com/oSparc/osparc-infra/-/issues/38
