### ISSUE TITLE
trafik error config

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#366]
Router defined multiple times with different configuration

https://monitoring.osparc-staging.io/graylog/messages/graylog_3/0d988831-592b-11ee-998c-0242ac120015

**Comment by pcrespov** [comment]
Hey @YuryHrytsuk , just FYI, you mentioned that this should be fixed with the latest update but I see that the error persist. Please check https://monitoring.osparc-staging.io/graylog/dashboards/650d4eacb3738c6c9e4a7a34
thx

**Comment by YuryHrytsuk** [comment]
It was fixed but not deployed (PR below). Today, I deployed this on aws strag, aws prod, dalco stag/prod, tip and master. This error log disappeared.

https://github.com/ITISFoundation/osparc-ops-environments/pull/346
