### ISSUE TITLE
Fails to push in the new staging url for the registry

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#367]
I noticed that the registry was constantly failing to get the manifest of `/v2/simcore/services/dynamic/s4l-stream/manifests/3.0.35`
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/5b5f81d0-b8bd-4945-8b3a-de125c503eb3)

The image seemed to be missing, when @mguidon tried to push it back,  we noticed that the push `registry.osparc-staging.io` **fails** 
```
docker push registry.osparc-staging.io/simcore/services/dynamic/s4l-stream:3.0.35
18aadbf436a4: Pushing [==================================================>]  10.75kB
5729f28ce5e1: Pushing [>                                                  ]    320kB/29.02MB
e335912578ab: Pushing [==================================================>]  5.761MB/5.761MB
2eee5cc41fa2: Pushing [>                                                  ]  529.4kB/213.8MB
c9f3f83feacf: Pushing [==================================================>]  4.608kB
93f3fb9ae4f6: Waiting 
687167eaa546: Waiting 
9d72957b2f37: Waiting 
f06a9caa5d1b: Waiting 
b49a9b9e42a4: Waiting 
2c644864e4e1: Waiting 
fbaa8e70f9f8: Waiting 
954c82bdeb5f: Waiting 
unauthorized: authentication required
make: *** [Makefile:148: publish-aws-staging] Error 1
```
Notice that the url is the new staging url. Using a push in `registry.staging.osparc.io` works
```
docker push registry.staging.osparc.io/simcore/services/dynamic/s4l-stream:3.0.35
```

It seems that the re-direction in place from the new to the old url of staging somehow loses the authentication!?

This is a problem detected some days ago. SEE 
https://mattermost.speag.com/z43/pl/f9inrdyrq3rgpy8b86npgmnnuo
https://mattermost.speag.com/z43/pl/yxubc54pyf8s5chwn4rgq5motw

**Comment by mrnicegyu11** [comment]
For docker `` and `` are two different registries. The DNS name resolves to the same IP, so the same machines, but for docker it looks like these are seperate registries. SO for me it seems reasonable that you have to login into both "registries" explicitly using `docker login` in order to push to both locations. Does it fix the issue if you explicitly run `docker login` against both DNS names of the registry?

**Comment by pcrespov** [comment]
> Does it fix the issue if you explicitly run `docker login` against both DNS names of the registry?

no. that is what we tried. Did you try and got different outcome?

**Comment by GitHK** [comment]
Graylog query to check if there are issues with unknown blobs `container_name:/.*registry.*/ AND log_level:ERROR AND "blob unknown to registry"`
