### ISSUE TITLE
webste_responsitivy tests in dalco-staging because https://testing.osparc-staging.speag.com does not exist anymore

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#368]
Fails with `'No address associated with hostname'` because URL `https://testing.osparc-staging.speag.com` does not exist anymore

It seems to me that this is somehow related with the change of url for staging? in https://github.com/ITISFoundation/osparc-ops-environments/issues/367
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/8af6a2bf-6200-425a-9682-a531c19bccef)

SEE details in https://git.speag.com/oSparc/e2e-portal-testing/-/jobs/3498368#L1308

Q: would it make sense to have a test that "pings" all expected entrypoints used in ops? We might detect earlier this issues when we change some base config?

**Comment by YuryHrytsuk** [comment]
This is a DNS issue. We are waiting for O+P to comment/resolve it.

**Comment by YuryHrytsuk** [comment]
Resolved by O+P
