### ISSUE TITLE
Remove `node.platform.os == linux` from this repo

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#369]
See https://github.com/ITISFoundation/osparc-simcore/pull/4571

**Comment by YuryHrytsuk** [comment]
Currently, I cannot find any `node.platform.os == linux` using VS Code global search. It relates to both `ops-env` and `ops-config`

**Comment by YuryHrytsuk** [comment]
It should have been removed during all the minor refactoring done
