### ISSUE TITLE
Add payments ENV

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#374]
Go through the PRs below and add all the env mentioned. Also talk to @pcrespov in case of any questions about the ENV values

- https://github.com/ITISFoundation/osparc-simcore/pull/4683
- https://github.com/ITISFoundation/osparc-simcore/pull/4676
- https://github.com/ITISFoundation/osparc-simcore/pull/4715
- https://github.com/ITISFoundation/osparc-simcore/pull/4717
- https://github.com/ITISFoundation/osparc-simcore/pull/4723

**Comment by pcrespov** [comment]
- @YuryHrytsuk for https://github.com/ITISFoundation/osparc-simcore/issues/4623 lets set `payments` scale=0

**Comment by YuryHrytsuk** [comment]
> * @YuryHrytsuk for [🚀 Release v1.59.0 osparc-simcore#4623](https://github.com/ITISFoundation/osparc-simcore/issues/4623) lets set `payments` scale=0 after checking that it starts and the env-vars are OK.

It is already set to `0` in aws, dalco and tip: https://github.com/ITISFoundation/osparc-ops-environments/pull/372

**Comment by YuryHrytsuk** [comment]
All ENV has been added along the way
