### ISSUE TITLE
AWS STAG: Registry bucket name misconfigured

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#388]
When deploying ops stack with new CI/CD pipeline on `aws stag`, the registry get the wrong bucket name `REGISTRY_STORAGE_S3_BUCKET`: `registry.osparc-staging.io`.

The correct value for `REGISTRY_STORAGE_S3_BUCKET` is `registry.staging.osparc.io`

**Comment by mrnicegyu11** [comment]
I have fixed this in https://github.com/ITISFoundation/osparc-ops-environments/commit/5829416337535ff83c99191f76b493644281c048
