### ISSUE TITLE
Traefik certificate generation is wrongly configured

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#394]
When traefik runs >= 1 replica, we need to ensure that certificates are only generated once (no matter how many replicas we have). Currently, as far as I understand, we generate every certificate N times where N is number of traefik replicas.

Here is a good official source explaining the issue: https://doc.traefik.io/traefik/v1.7/user-guide/cluster-docker-consul/#docker-configuration

**Comment by sanderegg** [comment]
@YuryHrytsuk traefik v1 is completely different from v2. be careful with this.

I think traefik can use something called consul which might help there, but not sure.

**Comment by YuryHrytsuk** [comment]
> @YuryHrytsuk traefik v1 is completely different from v2. be careful with this.
> 
> I think traefik can use something called consul which might help there, but not sure.
> 
> Just realized your link is about consul. I think they re-added it in v2 as well

Thank you for the note. You are indeed right that I point to `v1.7` while we are using `v2.10`. And `v1.X` and `v2.X` are quite different.

Here are a few related issues I found:
* Traefik v2.X HA https://github.com/traefik/traefik/issues/5426
* Traefik v1.X -> v2.X HA https://community.traefik.io/t/docker-swarm-running-traefik-in-replicated-mode-with-acme/6444
* Replicated traefik certificate race condition https://github.com/traefik/traefik/issues/8815

**Comment by YuryHrytsuk** [comment]
Traefik v2, HA & Letsencrypt

https://github.com/traefik/traefik/issues/5792

**Comment by YuryHrytsuk** [comment]
Docker Swarm x Traefik HA x Certificates management: https://www.reddit.com/r/Traefik/comments/xvym9a/is_there_a_best_practice_solution_for_distributed/

**Comment by YuryHrytsuk** [comment]
ACME Client Implementations:

https://letsencrypt.org/docs/client-options/

**Comment by YuryHrytsuk** [comment]
Example of using `traefik` with [user-defined certificates](https://doc.traefik.io/traefik/https/tls/#user-defined) (dynamic configuration):

https://medium.com/@clintcolding/use-your-own-certificates-with-traefik-a31d785a6441

**Comment by YuryHrytsuk** [comment]
My question regarding renewal of custom-managed certificates:

https://community.traefik.io/t/how-to-renew-update-user-defined-custom-certificates/20598

**Comment by YuryHrytsuk** [comment]
Implementation idea: use CI to generate certificates and then upload them to the servers running `traefik`. Then force traefik to reread the certificates.

Things to verify:
- [ ] touch traefik configuration will make traefik reload certificats
- [ ] traefik default certificate is used when no matching certificate is found

**Comment by YuryHrytsuk** [comment]
Traefik with custom certs. Guide:

https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/

**Comment by YuryHrytsuk** [comment]
It is deployed in master. Observe it for a week and then deploy to staging and prod.

The changes are propagated to:
- [X] master
- [ ] staging
- [ ] prod

**Comment by YuryHrytsuk** [comment]
Generate prod certificates for:
- [X] in-house master
- [X] nih staging
- [ ] nih prod
- [ ] [stag & prod] dalco
- [ ] tip
- [ ] sim4life
- [ ] aws master

**Comment by YuryHrytsuk** [comment]
The new cert management is used:
- [ ] in-house master
- [ ] aws master
- [ ] nih staging
- [ ] nih prod
- [ ] tip
- [ ] dalco stag
- [ ] dalco prod

**Comment by YuryHrytsuk** [comment]
Create traefik certificate generation CI Pipeline:

**Comment by YuryHrytsuk** [comment]
it is released to prod
