### ISSUE TITLE
Investigate: Accessible EC2 instance metadata via IP-based API

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#403]
See: 

https://towardsthecloud.com/amazon-ec2-instance-metadata
it actually works. you can get whatever info you like (even inside a container running on EC2) doing for example:
curl -s http://169.254.169.254/latest/meta-data/instance-type

Via @sanderegg 

![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/8209087/e761d409-10e1-458a-b9fd-ae6b1508724e)

SAN might be using this for autoscaling dask clusters, so talk to him before blocking this API

```[tasklist]
### Tasks
- [x] sim4life.io
- [x] osparc.io
- [x] staging.osparc.io
```

**Comment by sanderegg** [comment]
not sure you can block it by the way

**Comment by mrnicegyu11** [comment]
Seems it can be disabled

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html

Would it be ok if I disable it as a test on aws staging @sanderegg ?

**Comment by mrnicegyu11** [comment]
security wise it is a grey area I guess, none of the info is properly sensitive but getting to know our account id, the ami we run etc. gives options and places to look for further breaches. I think for now we can leave it on but we should keep it in the back of our mind.

**Comment by mrnicegyu11** [comment]
Fixed for the ZMT Deployment in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/commit/fe3a8d620185442db3d64a0f4f3691f983536770
