### ISSUE TITLE
Refactor configuration

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#404]
### Current state
Current env configuration logic causes many problems:
1. Tedious updates needed to be done in many [git] branches
2. Often miscellaneous missing env during releases

### Desired state
As discussed with @pcrespov, @mrnicegyu11 and @matusdrobuliak66 we want a new way of env configuration with
1. CI checks that config files are in sync (all have the same keys)
2. Developers setting up new env and propagate the new env to all deployments configs
3. The introduction of new ENV is done in 1 commit to a single branch

### First iteration: migrate CI/CDs

- [X] master
- [x] dalco prod
- [X] dalco stag
- [x] aws prod
- [X] aws stag
- [x] tip
- [x] sim4life

### Second iteration
- [x] Fail if `.env_devel` new ENV is not propagated to `repo.config`s (i.e. deployment configurations)

**Comment by mrnicegyu11** [comment]
Please check if and how this might relate to https://github.com/ITISFoundation/osparc-ops-environments/issues/177 at your conveniance ;)

**Comment by matusdrobuliak66** [comment]
> ### Current state
> Current env configuration logic causes many problems:
> 
> 1. Tedious updates needed to be done in many [git] branches
> 2. Often miscellaneous missing env during releases
> 
> ### Desired state
> As discussed with @pcrespov, @mrnicegyu11 and @matusdrobuliak66 we want a new way of env configuration with
> 
> 1. CI checks that config files are in sync (all have the same keys)
> 2. Developers setting up new env and propagate the new env to all deployments configs
> 3. The introduction of new ENV is done in 1 commit to a single branch

Yes, and my recommendation is to use a templating system (something like Ninja), which should give us enough flexibility to deal with some corner cases that might pop up (ex. if really for some reason some variable can not be defined somewhere, we can use if else Ninja statement, ...)

**Comment by sanderegg** [comment]
thank you to include me in these discussion @YuryHrytsuk . I also find the current state is not so great.

**Comment by YuryHrytsuk** [comment]
The first iteration was merged to master. I am attaching the PR's link below. The main idea of the first iteration is to move all `repo.config` files to a single branch and move as many secrets as possible to master folder in a new `configs` branch which contains all the `repo.configs`

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/88

**Comment by YuryHrytsuk** [comment]
AWS STAG CI/CD with a new configuration

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/98

**Comment by YuryHrytsuk** [comment]
DALCO STAG CI/CD with a new configuration

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/100

**Comment by YuryHrytsuk** [comment]
AWS PROD

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/109

**Comment by YuryHrytsuk** [comment]
TIP

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/107

**Comment by YuryHrytsuk** [comment]
DALCO PROD

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/104

**Comment by YuryHrytsuk** [comment]
sim4life

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/111

**Comment by YuryHrytsuk** [comment]
The part in the description is done. Let's continue from the https://github.com/ITISFoundation/osparc-ops-environments/issues/177
