### ISSUE TITLE
sim4life-io: cleanup before release

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#407]
- [ ] ~~Shut down bastion host~~
- [x] Clean tmp-files
- [ ] Have a pipeline that runs `rm` on `/tmp/z43_*` every sunday evening

**Comment by YuryHrytsuk** [comment]
@mrnicegyu11 is it still relevant?

**Comment by mrnicegyu11** [comment]
Yes, we basically need to do it the day beofre the release. You and @matusdrobuliak66 should be there to see why and what needs to be done. it is related to security only.

**Comment by YuryHrytsuk** [comment]
@mrnicegyu11 is it relevant

**Comment by mrnicegyu11** [comment]
closing wontfix, fine for now
