### ISSUE TITLE
nih-prod license: Remove EC2-NAT machines in favour of NAT-GW managed by AWS

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#408]

**Comment by mrnicegyu11** [comment]
The license server architecture on the zmt account works as of now, so it can be used as an example. On aws-staging and aws-prod, the aws cloud architecture should look like the one on the zmt aws account

**Comment by YuryHrytsuk** [comment]
Done. It should be merged and applied during next maintenance window:

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/517

**Comment by YuryHrytsuk** [comment]
Done
