### ISSUE TITLE
Dalco STAG: pg-backup is not deployed automatically

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#414]
### Actual behavior 
The `pg-backup` can only be deployed manually for dalco staging.

### Desired behaviour
The pg-backup is deployed automatically when running `make up-dalco` in `./services/pg-backup` for `dalco prod` like it does for [pgsql_query_exporter](https://github.com/ITISFoundation/osparc-ops-environments/blob/main/services/monitoring/pgsql_query_exporter_config.yaml.j2)

**Comment by mrnicegyu11** [comment]
Tracked in https://github.com/ITISFoundation/osparc-ops-environments/issues/453
