### ISSUE TITLE
Force start maintenance page pipeline stage fails

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#419]
### Actual behaviour
Running `force_start_maintenance_page` in a pipeline (deploying to staging or prod) fails

```bash
failed to create service maintenance-page_maintenance_page_hpcsciencestagingsim4lifecloud: Error response from daemon: rpc error: code = InvalidArgument desc = name must be 63 characters or fewer
```
Example pipeline: https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/jobs/3756817

### Expected behviour
Running `force_start_maintenance_page`  deploys maintenance page and succeeds

**Comment by mrnicegyu11** [comment]
fixed at least on staging, closing
