### ISSUE TITLE
aws-master

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#461]
Adds aws-master on the strides aws account:

- [x] billable vs non-billable product: is there only 1 entrypoint (e.g. osparc-testing.click) or several ? can we do billable and non billable product there? If not we will do I guess only billable
- [x] adminer is broken, as you said it looks like it's not the right version
- [x] graylog has no logs - not configured correctly
- [x] clusters-keeper cannot start at the moment because of resource shortage
- [x] we can scale down the catalog to 2 instances, same with the director --> https://github.com/ITISFoundation/osparc-ops-environments/pull/475
- [x] we can scale to 0 the dask-scheduler/dask-sidecar
- [x] prometheus seems connected
- [ ] grafana seems connected but without dashboards
- [x] redis commander is connected
- [x] rabbit is accessible
- [x] jaeger is connected
- [x] regarding autoscaling, the securitygroupIDs, etc are may be incorrect. probably the same for the clusters-keeper (@sanderegg will do it thx)
- [x] e2e-ops / credentials page
- [x] Add Products to googleslide
- [x] S3 bucket name issue. There are dots in the name (osparc.testing.click), that is not accepted by simcore and is very not recommended by AWS [reference], maybe change to ```osparc-testing-click``` ?(https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)
- [x] license server works
- [x] investigate cost increase

**Comment by YuryHrytsuk** [comment]
It is blocked before we decide if we continue with aws master

**Comment by mrnicegyu11** [comment]
done
