### ISSUE TITLE
Pin pre-pull dynamic sidecar image in EC2_INSTANCES_ALLOWED_TYPES

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#499]
Use the same value as in `DYNAMIC_SIDECAR_IMAGE`

@GitHK

**Comment by YuryHrytsuk** [comment]
It is on @sanderegg list and will be done in the future. I am unassigning myself now.

**Comment by sanderegg** [comment]
should be fixed by https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/297
@YuryHrytsuk please validate thanks.

**Comment by YuryHrytsuk** [comment]
thank you, @sanderegg!
