### ISSUE TITLE
Add OPS Test to ensure that terraform is up-to-date

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#500]
### Desired behavior
* There is a test that fails if terraform (for every deployment using it) is not update to date. 
* This test is a part of our board of tests and is being checked on daily basis

**Comment by mrnicegyu11** [comment]
This should go as discussed into e2e-ops, where we would clone and hcekout the HEAD of `configs` branch os osparc-ops-deployment-configuration, go to the right folder, go then to the terraform folder and run `init,``plan`, and assert that the plan has 0 changes. It should run 1-4 times per day

**Comment by YuryHrytsuk** [comment]
Tasks:
- [ ] AWS Master
- [ ] NIH STAG
- [ ] NIH PROD
- [ ] S4L PROD
