### ISSUE TITLE
Add appmotion endpoint certificate test

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#502]
The certificate should be tests with other certificates in OPS tests

**Comment by mrnicegyu11** [comment]
done in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/299

**Comment by YuryHrytsuk** [comment]
> done in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/299

How does it affect this [e2e-ops test](https://git.speag.com/oSparc/e2e-ops/-/tree/main/scripts/check-ssl-certificates?ref_type=heads)?

**Comment by mrnicegyu11** [comment]
https://git.speag.com/oSparc/e2e-ops/-/merge_requests/193

**Comment by mrnicegyu11** [comment]
done
