### ISSUE TITLE
Graylog master constantly restarting

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#506]
This error shows repetitively 
```
2024-01-12 09:18:50,535 ERROR: org.graylog.events.notifications.EventNotificationHandler - Couldn't find job definition for notification <<function configure_slack_notifications at 0x7f2b0d0f44c0>>

```
and finally the service is unhealthy and restarted

**Comment by mrnicegyu11** [comment]
This seems related to the graylog email alerst that go to mattermost. These alerts are set-up automatically via the CI, which runs `cd services/graylog && make configure`. Since they are barely used we can remove these alerts maybe?

**Comment by YuryHrytsuk** [comment]
Repeats https://github.com/ITISFoundation/osparc-ops-environments/issues/512
