### ISSUE TITLE
exporters in master's monitoring-stack do not start

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#511]
- [ ] dcgm-exporter
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/70374c3e-0633-4a09-b9e5-a94f4602167c)
- [ ] nvidia exporter
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/9197fc53-ecb0-4a2c-8175-c1b9e2edc76c)
- [x] smokeping prober
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/6b29b076-34fc-43c0-b86f-42b60e78ce7c)

**Comment by mrnicegyu11** [comment]
I am happy to report that this was fixed :--)

![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/8209087/3ac3bd40-e1f3-466b-b852-1c1ee8380713)
