### ISSUE TITLE
One `nvidia/dcgm-exporter` service in master cannot start

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#532]
- Reports fatal error: Error adding GPU 0 to group: This GPU is not supported by DCGM.

<img width="1242" alt="image" src="https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/b500287b-f751-4da9-a910-198d45161a3d">

**Comment by mrnicegyu11** [comment]
1. Try to find out which GPUs (gaming GPUs) are supported by the DGCM exporter
2. Have IT change the GPU on master04 only, potentially have Nik buy one

**Comment by YuryHrytsuk** [comment]
The GPU and Harddriver is being tested by IT team

**Comment by YuryHrytsuk** [comment]
Master 04 is back, up and running. DCGM exporter works as expected
