### ISSUE TITLE
Investigate Restarting Graylog errors on master

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#535]
This is happening again in master ... fails, get unhealthy  and the swarm shuts it down

<img width="1399" alt="image" src="https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/47dcb90c-d785-4c48-84ae-ae587f2d43f8">

_Originally posted by @pcrespov in https://github.com/ITISFoundation/osparc-ops-environments/issues/512#issuecomment-1916409433_

**Comment by mrnicegyu11** [comment]
`SIGNAL` recieved indicates that graylog had a RAM spike and was reaped by the OOM killer.

**Comment by pcrespov** [comment]
This still an issue. 
<img width="565" alt="image" src="https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/cfcebc99-923a-4bc9-b408-083c66938e15">
:-(
