### ISSUE TITLE
directorv2 (and other services from the osparc-stack) is being started in ops2 manager node

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#547]
![Pasted image 20240205110251](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/f8bf57bb-089e-45bd-9810-e781d34fc408)

NOTE: that `ops2` is not a strong machine and this service needs quite some resources.
thx

**Comment by mrnicegyu11** [comment]
This is not an issue at all from the technical side, but we fully understand that seeing a director-v2 running on a node named "ops" seems wrong when debugging. We will want to address this in the future, but not this sprint, since it is purely cosmetic.

**Comment by mrnicegyu11** [comment]
Add placement-constraint `ops!=true` should fix this

**Comment by YuryHrytsuk** [comment]
> Add placement-constraint `ops!=true` should fix this

This will not work because on some deployments we have only 1 manager which is also OPS, or all managers are also OPS
