### ISSUE TITLE
Introduce backups for Appmotion DB

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#549]
```[tasklist]
### Tasks
- [ ] aws master
- [ ] nih stag
- [ ] sim4life
- [ ] aws tip
```

**Comment by mrnicegyu11** [comment]
This will be done with RDS snapshotting

**Comment by mrnicegyu11** [comment]
blocked by https://github.com/ITISFoundation/osparc-ops-environments/issues/554

**Comment by YuryHrytsuk** [comment]
Duplicate https://github.com/ITISFoundation/osparc-ops-environments/issues/554
