### ISSUE TITLE
Logs missing when ingress docker port for graylog on IP `0.0.0.0` is used

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#551]
This was reported by @sanderegg , please quickly write a short confirmation, if changing from the graylog IP `0.0.0.0` to an explicit (internet vailable or private range) IP fixed the issue for you, thanks!

CC @sanderegg

**Comment by YuryHrytsuk** [comment]
Articles to read:
* https://stackoverflow.com/questions/51404544/docker-containers-in-stacks-within-ec2-instance-do-not-inherit-dns-nameserver

**Comment by YuryHrytsuk** [comment]
The original title implied that the problem is in `0.0.0.0` IP address. I am changing this issue to an overall problem of graylog logs missing.

`Graylog logs are missing when ingress docker port for graylog on IP 0.0.0.0 is used`

**Comment by YuryHrytsuk** [comment]
As of now all is working and I don't see any actions required.

Incidents and history: https://z43.fogbugz.com/f/cases/193990/
