### ISSUE TITLE
Procedure for terraform

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#553]
- On AWS master, terraform plan and apply will always run at night as a CI/CD pipeline somehow.

- On staging/production deployments, only DevOps (@matusdrobuliak66 @YuryHrytsuk @mrnicegyu11 ) run `terraform apply`, either from CLI or the CI pipeline

- Only DevOps (@matusdrobuliak66 @YuryHrytsuk @mrnicegyu11 ) merge terraform PRs and will consider when and how to run `apply` after merging

Actionable:
- [x] Implement CI/CD functionality
- [x] Clarify and put into README/docs

**Comment by YuryHrytsuk** [comment]
readme/docs --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/363/diffs
