### ISSUE TITLE
Move per-deployment assets from this repo & legacy repos to osparc-config

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#555]
All per-deployment config, secret,s, assets, such as:
- Maintenance Pages HTML
- Passwords
- Customizations oer deployment/product
... now are placed in the git repo osparc-configs.
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/546
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/229
```

**Comment by YuryHrytsuk** [comment]
Closing as all tasks mentioned are done
