### ISSUE TITLE
config/users/user_config.yml relies on pyenv/python for some obscure reasons

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops-environments#559]
as asked by @mrnicegyu11 this should be fixed sooner rather than later.
reference:
https://git.speag.com/oSparc/osparc-infra/-/merge_requests/203#note_183682

**Comment by mrnicegyu11** [comment]
Addressed in https://git.speag.com/oSparc/osparc-infra/-/merge_requests/224
