### ISSUE TITLE
Prune products on NIH deployment

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-ops-environments#561]
Currently we have only 2 active products on this deployment. `osparc` and `s4llite`. The other two should be removed.

![Screenshot 2024-02-15 at 09 52 45](https://github.com/ITISFoundation/osparc-ops-environments/assets/5694077/9742b819-2348-4db7-9f78-6001fb380674)

**Comment by pcrespov** [comment]
Follwed up in https://github.com/ITISFoundation/osparc-simcore/issues/5337
