### ISSUE TITLE
Make `sim4life.cloud` an **alias** of `sim4life.io`

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#564]
We are going to remove `s4l` product in `osparc.io` deployment. This product is associated to `sim4life.cloud`. We will reuse this domain as an alias to `sim4life.io`.

**Comment by mrnicegyu11** [comment]
done 
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/8209087/f92a3c6a-1238-469e-825b-6ff80ede6510)
