### ISSUE TITLE
Set AWS lifecycle rule for incomplete multipart uploads

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops-environments#598]
@sanderegg added a lifecycle rule in AWS-master in order to automatically delete incomplete multipart uploads older than 7 days.

NOTE: the rule is assigned to a bucket

according to @mrnicegyu11 this should be adapted in terraform and deployed in all AWS deployments:
- import the rule in terraform (or feel free to overwrite it to change the naming if inconvenient)
- propagate to all buckets in AWS

**Comment by mrnicegyu11** [comment]
taking action here...

**Comment by mrnicegyu11** [comment]
Done on
- [ ] zmtmaster
- [ ] nihstaging
- [ ] nihprod
- [ ] zmtprod

**Comment by mrnicegyu11** [comment]
done
