### ISSUE TITLE
Enhance routing of ind. maintenance page on aws

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#640]
On AWS using the inp. maintenance page with AWS loadBalancing, the following is the desirable scenario w.r.t. routing:

- "Simcore" routes, including the landingpage e.g. `osparc.io`, and `UUID.services.osparc.io` iframe routes, should be redirected to the ind. maintenance page
- Monitoring and ops-routes, such as `monitoring.osparc.io/portainer` or `admin.osparc.io` or `registry.osparc.io` should still be accessible, since the dev-team might want to use them for debugging.

Currently, to the best of my knowledge, the latter is not possible.

**Comment by mrnicegyu11** [comment]
Possible improvement: 
- [ ] Make sure that ops-domains are explicitly defined in the DNS-Server/Service.
- [ ] Conduct test on NIH staging

**Comment by YuryHrytsuk** [comment]
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/604
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/596/diffs

**Comment by YuryHrytsuk** [comment]
Reopen until PRs above are merged
