### ISSUE TITLE
monitoring internal network IP exhaustion

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#665]
This happens on S4L every week. The Network size is too small compared to the number of containers we need to run. 

Possible solutions:
* drain nodes before removing then [proper solution] @sanderegg 
* bigger [external] network managed manually
* change docker swarm default subnets size
* get rid of internal monitoring network 
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5827
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/674
```

**Comment by sanderegg** [comment]
all tasks implemented
