### ISSUE TITLE
Operations: Move ops stack to Kubernetes

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-ops-environments#671]
### Discussed in https://github.com/ITISFoundation/osparc-simcore/discussions/5567

<div type='discussions-op-text'>

<sup>Originally posted by **mguidon** March 28, 2024</sup>
To gather inside and experience for the future.</div>
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/669
```

**Comment by YuryHrytsuk** [comment]
Currently, it is redundant. Closing it. We will keep track of this issue in https://github.com/ITISFoundation/osparc-ops-environments/issues/618
