### ISSUE TITLE
Working Group: Move products between deployments

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#672]
Ideas:
is it maybe reasonable to first create a visualization of what consitutes a product, in order to encapsulate it as an artifact, and export it?

a product is not only the entry in the productsDB table, but also connected projects, users, wallets, payments, frontend, etc.etc.

**Comment by matusdrobuliak66** [comment]
![440871009_3694197630909287_7269496293591851454_n](https://github.com/ITISFoundation/osparc-ops-environments/assets/60785969/7fa0285a-d25b-4257-8168-4c56e5d54ddc)

**Comment by mrnicegyu11** [comment]
working group was done.

**Comment by mrnicegyu11** [comment]
Cross -product exporting was requested by LK `I'll tell them to make an account and try it out. Can they transfer the simulations? Or at least the model?`
