### ISSUE TITLE
Configure proper AIRAM resources for each deployment

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#713]
## Story
Currently, we have deployments with Docker Nodes where AIRAM is set to hundreds / thousands and we have deployment with Docker Nodes with AIRAM set to 1

## Desired state
AIRAM is set to the same value on all deployments

fyi: @GitHK @mrnicegyu11 @mguidon

**Comment by mrnicegyu11** [comment]
Closed and supercede by https://github.com/ITISFoundation/osparc-ops-environments/issues/869
