### ISSUE TITLE
Investigate at pre-pulling script failure

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#721]
See https://git.speag.com/oSparc/sparc-external/-/pipelines, raised by @wvangeit

**Comment by wvangeit** [comment]
(also related: https://github.com/ITISFoundation/osparc-issues/issues/1565)

**Comment by mrnicegyu11** [comment]
Fix proposed in https://git.speag.com/oSparc/sparc-external/-/merge_requests/367

**Comment by mrnicegyu11** [comment]
fixed

**Comment by wvangeit** [comment]
Thanks a lot @mrnicegyu11 !
