### ISSUE TITLE
master: traefik missing port for registry pull through cache

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#730]
- open graylog dashboard in master
- add filter `log_service:traefik_traefik`
- `traefik` service periodically fails in
time="2024-08-12T11:30:43Z" level=error msg="service \"registry-registry-pull-through-cache\" error: port is missing" providerName=docker container=registry-registry-pull-through-cache-****

![image](https://github.com/user-attachments/assets/a6c6cbd1-2385-45d5-a38a-1a3c54a3502c)

Seems to be a misconfiguration

**Comment by mrnicegyu11** [comment]
This is a new feature by @YuryHrytsuk , please comment briefly

**Comment by YuryHrytsuk** [comment]
> This is a new feature by @YuryHrytsuk , please comment briefly

Yes. We do not use `registry-pull-through-cache` in in-house master. I will take care of it soon.

Thanks
