### ISSUE TITLE
HIGH PRIO: Grafana dashboards broken on dalco-staging

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#790]
Likely due to grafana major version upgrade

**Comment by mrnicegyu11** [comment]
@YuryHrytsuk this might be a wontfix since we want to split the existing dalco cluster into two seperated machines (one for staging, one for prod), once tip.itis.swiss is phased out and we have those machines at our disposal.

Do you agree or disagree?

**Comment by YuryHrytsuk** [comment]
> @YuryHrytsuk this might be a wontfix since we want to split the existing dalco cluster into two seperated machines (one for staging, one for prod), once tip.itis.swiss is phased out and we have those machines at our disposal.
> 
> Do you agree or disagree?

It makes sense. We can set it as "Blocked". The Ops Stack test fails. Shall we comment out Grafana Dashboard test?

**Comment by mrnicegyu11** [comment]
Yes I think this is the way to go, let us first inform or ask the team at the daily

**Comment by mrnicegyu11** [comment]
the team agreed, this is a wontfix.
