### ISSUE TITLE
pre-commit hook `validate-maintenance-page-html` does not capture missing maintenance pages

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#806]
We introduced new domains (deployment_fqdns) to AWS Master which broke `deploy_maintenance_page` CI task. The pre-commit hook shall capture this

```[tasklist]
### Wishes for Deployment CI Tests
- [X] easy to run same tests locally
- [X] easy to add new tests
- [X] flexibility in tools for tests (e.g. python or bash script)
```
Done :heavy_check_mark:  in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1093

**Comment by mrnicegyu11** [comment]
The pre-commit hook should be moved to a CI stage test
