### ISSUE TITLE
AWS Docker Image Pulling: avoid using public internet

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#812]
AWS Docker Image Pulling costs are very high because we go outside the internal network and it costs a lot. We should stay within private internet while docker image pulling.

:warning: we need to have an opportunity to push images to registry from the outside (registry-syncer)

**Comment by mrnicegyu11** [comment]
To the best of our knowledge this was fixed with the S3 VPC Endpoint, but this needs to be validated

**Comment by mrnicegyu11** [comment]
I have checked all non-nih deployments and it indeed looks like the cost for "NAT gateway Bytes" are drastically reduced, to a very tolerable average of 5$ per day

**Comment by mrnicegyu11** [comment]
re-opening, not sure if fixed on nih-prod and nih-stag
