### ISSUE TITLE
ValidateDotEnvFile pre-commit hook failing

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops-environments#837]
![Image](https://github.com/user-attachments/assets/67f21cb7-f33b-4471-90fc-63eb01f53bce)

![image](https://github.com/user-attachments/assets/aea74c46-c698-4b57-8c1c-30bd523fcf34)

**Comment by YuryHrytsuk** [comment]
Fixed in https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/1004
