### ISSUE TITLE
www. traefik redirect is broken

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#874]
The middlewares in traefik, on all deployments, redirecting e.g. `www.osparc-staing.io` to `osparc-staging.io` don't work anymore. In all likelyhood this stopped working when we went from traefik v2 to traefik v3.

Follow-Ups:
- Create e2e-ops tests that check that the redirects work
- Fix the redirects themselves

**Comment by YuryHrytsuk** [comment]
Should we just remove it altogether (i.e. abandon `www` domains)?
