### ISSUE TITLE
Introduce python linters in `osparc-ops-environments`

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#97]
These variable names are really difficult to read as a single word: use ``snake_case`` for variables and ``CamelCase`` for classes. I would start considering re-formatting all the python code in this repo as in ospar-simcore.

Same for the filenames.

_Originally posted by @pcrespov in https://github.com/ITISFoundation/osparc-ops-environments/pull/91#discussion_r1086391857_

**Comment by YuryHrytsuk** [comment]
Black formatter is already in

**Comment by YuryHrytsuk** [comment]
the next step is to introduce python linters that will enforce code standards (e.g. `pep 8`). However, I don't see much need at this stage

**Comment by pcrespov** [comment]
> the next step is to introduce python linters that will enforce code standards (e.g. `pep 8`). However, I don't see much need at this stage

@YuryHrytsuk if it is "the next step" and you are closing the issue I wonder where did you moved this topic? Do you have a new list?

**Comment by YuryHrytsuk** [comment]
> > the next step is to introduce python linters that will enforce code standards (e.g. `pep 8`). However, I don't see much need at this stage
> 
> @YuryHrytsuk if it is "the next step" and you are closing the issue I wonder where did you moved this topic? Do you have a new list?

I reopened this issue and changed the title
